#!/bin/sh
/usr/local/bin/convert -resize 250 orig/cral_logo.jpeg mid/cral_logo.png
/usr/local/bin/convert -resize 250 orig/gepi_logo.jpg mid/gepi_logo.png
/usr/local/bin/convert -resize 250 orig/ipag_logo.png mid/ipag_logo.png
/usr/local/bin/convert -resize 250 orig/irap_logo.jpeg mid/irap_logo.png
/usr/local/bin/convert -resize 250 orig/lagrange_logo.png mid/lagrange_logo.png
/usr/local/bin/convert -resize 250 orig/lam_logo.jpg mid/lam_logo.png
/usr/local/bin/convert -resize 250 orig/lesia_logo.png mid/lesia_logo.png
/usr/local/bin/convert -resize 250 orig/efisoft_logo.png mid/efisoft_logo.png

/usr/local/bin/convert -resize 100 orig/cral_logo.jpeg small/cral_logo.png
/usr/local/bin/convert -resize 100 orig/gepi_logo.jpg small/gepi_logo.png
/usr/local/bin/convert -resize 100 orig/ipag_logo.png small/ipag_logo.png
/usr/local/bin/convert -resize 100 orig/irap_logo.jpeg small/irap_logo.png
/usr/local/bin/convert -resize 100 orig/lagrange_logo.png small/lagrange_logo.png
/usr/local/bin/convert -resize 100 orig/lam_logo.jpg small/lam_logo.png
/usr/local/bin/convert -resize 100 orig/lesia_logo.png small/lesia_logo.png
/usr/local/bin/convert -resize 100 orig/efisoft_logo.png small/efisoft_logo.png